assignment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('todo', include('todo.urls'))
]

authentication/urls.py
from django.urls import path
from authentication import views

app_name = 'authentication'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('registration', views.registration_view, name='registration')
]

todo/urls.py
from django.urls import path

from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.home, name='home'),
    path('add', views.creation_form, name='add'),
    path('finish/<task_id>', views.finish, name='finish'),
    path('clear', views.clear_list, name='clear'),
    path('logout_user', views.logout_user, name='logout_user')
]

authentication/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models
from django.conf import settings

class Task(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    
    task_name = models.CharField(max_length=100)
    
    is_finished = models.BooleanField(default=False)

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        
        if form.is_valid():
            login(request, form.get_user())
            return redirect('todo:home')
    else:
        form = AuthenticationForm()
    
    return render(request, 'authentication/login.html', { 'form': form })

def registration_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        
        if form.is_valid():
            form.save()
            
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1'],
            )
            login(request, user)
            
            return redirect('todo:home')
    else:
        form = UserCreationForm()
    
    return render(request, 'authentication/registration.html', { 'form': form })

todo/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout

from todo.models import Task

def home(request):
    if request.user.is_authenticated:
        all_tasks = Task.objects.filter(user__exact=request.user.id)
        
        pending_tasks  = [task for task in all_tasks if not task.is_finished]
        finished_tasks = [task for task in all_tasks if task.is_finished]
        
        return render(request, 'todo/index.html', { 'pending_tasks': pending_tasks, 'finished_tasks': finished_tasks })
    
    return redirect('authentication:login')

def creation_form(request):
    user = request.user
    
    task = Task(user=user, task_name=request.POST['task_name'])
    task.save()
        
    return redirect('todo:home')

def finish(request, task_id):
    task = Task.objects.get(pk=task_id)
    task.is_finished = True
    
    task.save()
    
    return redirect('todo:home')

def clear_list(request):
    Task.objects.all().delete()
    return redirect('todo:home')

def logout_user(request):
    logout(request)
    return redirect('authentication:login')

authentication/templates/authentication/login.html
<!DOCTYPE html>
<html>
    <head>
        <title>Login</title>
    </head>
    <body>
        <h2>Login</h2>
        
        <form class="site-form" action="{% url 'authentication:login' %}", method='POST'>
            {% csrf_token %}
            {{ form }}
            
            <input type="submit" value="Login">
        </form>

        <a href="{% url 'authentication:registration' %}">Register</a>
    </body>
</html>

authentication/templates/authentication/registration.html
<!DOCTYPE html>
<html>
    <head>
        <title>Registration</title>
    </head>
    <body>
        <h2>Registration</h2>
        
        <form class="site-form" action="{% url 'authentication:registration' %}", method='POST'>
            {% csrf_token %}
            {{ form }}

            <input type="submit" value="Register">
        </form>

        <a href="{% url 'authentication:login' %}">Login</a>
    </body>
</html>

todo/templates/todo/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<title>ToDo list</title>
	</head>
	<body>
        <h2 style="maring-bottom:0">Hello, {{ user.username }}! <a href={% url 'todo:logout_user' %}>Log out</a></h2>
        
        <form action="{% url 'todo:add' %}" method="POST">
            {% csrf_token %}
            <input type="text" required placeholder="Enter your task" name="task_name">
            <button type="submit">Add task</button>
        </form>

        <div>
            <a href="{% url 'todo:clear' %}">
                <button type="button">
                    Clear list
                </button>
            </a>
        </div>

        {% if pending_tasks %}
            <h3>Tasks:</h3>
            <ul>
                {% for task in pending_tasks %}
                    {% if not task.is_finished %}
                        <a href="{% url 'todo:finish' task.id %}"><li>{{ task.task_name }}</li></a>
                    {% endif %}
                {% endfor %}
            </ul>
        {% endif %}

        {% if finished_tasks %}
            <h3>Completed tasks:</h3>
            <ul>
                {% for task in finished_tasks %}
                    {% if task.is_finished %}
                        <strike><li>{{ task.task_name }}</li></strike>
                    {% endif %}
                {% endfor %}
            </ul>
        {% endif %}
	</body>
</html>